### ISSUE TITLE
On Beaglebne errors

### ISSUE THREAD

**Issue by ghost** [vzaigrin/libi2c#1]
In the blog the write code has

```
    msg.slave = slave;
    msg.flags = 0;
```

in git the code is

```
    msg.slave = slave << 1 | !IIC_M_RD;
    msg.flags = !IIC_M_RD;

```
anyway both versions returns .

```
Failed to acquire bus access or talk to slave /dev/iic2: 3c err=-1 
I2CRDWR Writing: Bad address
cannot init 
```
the i2c dev is there

```
Hardware may not support START/STOP scanning; trying less-reliable read method.
Scanning I2C devices on /dev/iic2: 3c 

```
Any ideas.
Thank you.

**Comment by vzaigrin** [comment]
Hi. What version of OS do you use? Did you try scan I2C bus first?

**Comment by ghost** [comment]
Hi, Thank you. 
Is resolved. Is posted at BSD forum. Was 11.3 on BBB
[here](https://forums.freebsd.org/threads/i2c-on-beaglebone.72449/)
